version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./backend:/server
      - /server/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
    stdin_open: true
    depends_on:
      - backend
